### ISSUE TITLE
Add ability to chain/combine multiple fetchers into a group or dependency chain

### ISSUE THREAD

**Issue by aeneasr** [ory/redux-saga-fetch#12]
Assuming

```js
const sagaFetcher = createSagaFetcher({
  article: {
    fetcher: (id) => getUsersFromAPI(id)
  },
  createArticle: {
    fetcher: (payload) => createArticleAtAPI(payload)
  }
})
```

it would be very helpful if we could group those two fetchers into one, so we don't encounter race conditions on e.g. bad network connectivity.

Two ideas, the first one is grouping:

```js
const sagaFetcher = createSagaFetcher({
  article: {
    fetcher: (id) => getUsersFromAPI(id),
    group: 'article'
  },
  createArticle: {
    fetcher: (payload) => createArticleAtAPI(payload),
    group: 'article'
  }
})
```

The second is dependency (gives us more accuracy over controls but is also more work to define):

```js
const sagaFetcher = createSagaFetcher({
  article: {
    fetcher: (id) => getUsersFromAPI(id),
    dependsOn: ['createArticle']
  },
  createArticle: {
    fetcher: (payload) => createArticleAtAPI(payload)
  }
})
```

**Comment by zepatrik** [comment]
So `dependsOn` is like wait for these to finish if they are fetching?

**Comment by aeneasr** [comment]
Yup. If we have more actions (delete, update, create) this will become more work to define. On the other hand, `create` does not really need `get` first (that's why `dependsOn` makes more sense here). I am fine with both approaches as they both have their up and downsides.

**Comment by zepatrik** [comment]
I think the grouping is more straight forward and sufficient for now, and way easier to implement on both sides. It behaves a bit like a semaphore, locking the key.

**Comment by zepatrik** [comment]
for a bit more control we can enable groups to be an array too, so you can add one action to more groups. that way it is possible to recreate the behavior of `dependOn` because you can make groups of two following actions and chain it that way

**Comment by aeneasr** [comment]
Yeah I agree, let's stick to groups. If we really want `dependsOn` it will be as a new feature
